LTO_ENABLE = yes    
CONSOLE_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
DEFERRED_EXEC_ENABLE = yes

OLED_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_SPLIT = yes

ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

GRAVE_ESC_ENABLE = no 
TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no